### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by thororen1234** [Equicord/Companion#1]

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/34654f1b-245d-4741-a798-693518a80c7c)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/f92c7511-3094-4c8b-8f94-8ef80e9780ba)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/248a7f21-d599-4cc1-b5f1-197a10331997)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/49782a41-ceb5-4d34-a7e6-d4d84a78a3d9)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/4242d2ba-9d8a-456d-9340-e19546991ca7)

**Comment by verysillycat** [comment]
![me](https://github.com/user-attachments/assets/99d80320-4eb1-4809-b35e-11d02921a7d9)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/e69667fa-41df-408a-9b98-df8c0c9e19e2)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/d0965636-bc83-4f1e-b734-354ef956f368)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/b35c4cd5-19fe-45f5-9e1d-6c3a00563a6d)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/eb9af701-1395-4cec-92d9-54185f2713cd)

**Comment by thororen1234** [comment]
![image](https://github.com/user-attachments/assets/0f3328cb-ae63-4a19-8c28-5637e931b09a)

**Comment by KrstlSkll69** [comment]
![](https://cdn.nest.rip/uploads/28abcfc3-ebb2-495b-aaa5-16a7d956b703.gif)
